### ISSUE TITLE
Cache Persistency throws CannotMapTypeException 

### ISSUE THREAD

**Issue by XPOL555** [thecodingmachine/graphqlite-laravel#17]
Hello there!

After 2+ hours of debugging this production error
```log
TheCodingMachine\GraphQLite\Mappers\CannotMapTypeException: For return type of 
App\Company::getEmployees, cannot map class "App\Employee" to a known GraphQL type. 
Check your TypeMapper configuration. 
in file /var/app/current/vendor/thecodingmachine/graphqlite/src/Mappers/CannotMapTypeException.php on 
line 25
```

I discovered it was caused by the caching system used by GraphQLite.

Running

    $ sudo rm -rf /tmp/symfony-cache/ /tmp/graphqlite.*

solved my issue due to re-generation of Schema by the service provider (since APCU is not available in my production machine [GQLite will fallback](https://github.com/thecodingmachine/graphqlite-laravel/blob/master/src/Providers/GraphQLiteServiceProvider.php#L84) to [\Symfony\Component\Cache\Simple\PhpFilesCache](https://symfony.com/doc/current/components/cache/adapters/php_files_adapter.html)

Using Laravel 6, GraphQLite 4 (dev-master ATOW)

@moufmouf i am tagging you cause idk if should be relevant and, for me, the caching fallback system should be the Laravel cache not a symfony one.

**Comment by moufmouf** [comment]
Hey @XPOL555 ,

Sorry to respond so late, for some reason, I did not see the notification.
I'll definitely have a look at this!

**Comment by moufmouf** [comment]
Ok. Note to myself: GraphQLite uses a PSR-16 driver. By default, the cache from the graphqlite-laravel extensionis "symfony/cache". But this one is not compatible with Laravel caches, and therefore, it is not purged when "artisan cache:clear" is triggered.

We need to find a way to make sure the cache is purged in "artisan cache:clear".

This can probably be done by writing a wrapper around the PSR-16 cache and registering it in Laravel:

https://laravel.com/docs/5.7/cache#adding-custom-cache-drivers

**Comment by moufmouf** [comment]
More notes: it seems Laravel is emitting an event when clearing the cache:

https://github.com/illuminate/cache/blob/master/Console/ClearCommand.php#L63-L65

I can probably hook on this to purge the PSR-16 cache.

**Comment by XPOL555** [comment]
Great! @moufmouf glad to help
