### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by alanwojcik** [thecodingmachine/graphqlite-laravel#37]
Hey,

package right now is not supporting laravel 9. Can we get laravel 9 support? As I can see, everything is working, it's only need to add support for illuminate/console&container&support&cache to version ^9

**Comment by seifane-wise** [comment]
@alanwojcik I opened this PR https://github.com/thecodingmachine/graphqlite-laravel/pull/38 because I was having the same issue.

**Comment by moufmouf** [comment]
Closed by #38. Thanks @seifane-wise !
